//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSheet.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string AddressBlock {
            get {
                return ResourceManager.GetString("AddressBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project added!.
        /// </summary>
        public static string AlertProj {
            get {
                return ResourceManager.GetString("AlertProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create an invoice of this task?.
        /// </summary>
        public static string AlertTask {
            get {
                return ResourceManager.GetString("AlertTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarAdd {
            get {
                return ResourceManager.GetString("AppBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string AppBarBack {
            get {
                return ResourceManager.GetString("AppBarBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AppBarDelete {
            get {
                return ResourceManager.GetString("AppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice.
        /// </summary>
        public static string AppBarInvoice {
            get {
                return ResourceManager.GetString("AppBarInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create invoice.
        /// </summary>
        public static string AppBarInvoiceText {
            get {
                return ResourceManager.GetString("AppBarInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string AppBarResetText {
            get {
                return ResourceManager.GetString("AppBarResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save task.
        /// </summary>
        public static string AppBarSaveText {
            get {
                return ResourceManager.GetString("AppBarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string AppBarSelect {
            get {
                return ResourceManager.GetString("AppBarSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string AppBarShare {
            get {
                return ResourceManager.GetString("AppBarShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timesheet.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMESHEET.
        /// </summary>
        public static string ApplicationTitleUpper {
            get {
                return ResourceManager.GetString("ApplicationTitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AskN {
            get {
                return ResourceManager.GetString("AskN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AskY {
            get {
                return ResourceManager.GetString("AskY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank name.
        /// </summary>
        public static string BankInfoBlock {
            get {
                return ResourceManager.GetString("BankInfoBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beneficiary.
        /// </summary>
        public static string BenefBlock {
            get {
                return ResourceManager.GetString("BenefBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bill to.
        /// </summary>
        public static string BillBlock {
            get {
                return ResourceManager.GetString("BillBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string ButtonActionPauseText {
            get {
                return ResourceManager.GetString("ButtonActionPauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string ButtonActionResumeText {
            get {
                return ResourceManager.GetString("ButtonActionResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start task.
        /// </summary>
        public static string ButtonActionStartText {
            get {
                return ResourceManager.GetString("ButtonActionStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ButtonBegin {
            get {
                return ResourceManager.GetString("ButtonBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose an exitisting task to resume.
        /// </summary>
        public static string ChooseTaskBlock {
            get {
                return ResourceManager.GetString("ChooseTaskBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company.
        /// </summary>
        public static string CompanyBlock {
            get {
                return ResourceManager.GetString("CompanyBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concerns.
        /// </summary>
        public static string ConcernBlock {
            get {
                return ResourceManager.GetString("ConcernBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task removed.
        /// </summary>
        public static string ConfirmTask {
            get {
                return ResourceManager.GetString("ConfirmTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks removed.
        /// </summary>
        public static string ConfirmTasks {
            get {
                return ResourceManager.GetString("ConfirmTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DataBlock {
            get {
                return ResourceManager.GetString("DataBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DateBlock {
            get {
                return ResourceManager.GetString("DateBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string DescBlock {
            get {
                return ResourceManager.GetString("DescBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSheet will help you when you start a new task or maybe when you need to resume an existing; providing you a simple manner to keep track the spent time and also, you will be able to create an invoice about that task. Simple, clean and useful companion for all the activities. Go ahead and taste it!.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string DurationBlock {
            get {
                return ResourceManager.GetString("DurationBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;TIMESHEET - Feddback&quot;.
        /// </summary>
        public static string EmailFeedBack {
            get {
                return ResourceManager.GetString("EmailFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string EmailInvoice {
            get {
                return ResourceManager.GetString("EmailInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iban.
        /// </summary>
        public static string IBANBlock {
            get {
                return ResourceManager.GetString("IBANBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice #.
        /// </summary>
        public static string InvoiceIDBlock {
            get {
                return ResourceManager.GetString("InvoiceIDBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice data.
        /// </summary>
        public static string InvoiceSettings {
            get {
                return ResourceManager.GetString("InvoiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NameBlock {
            get {
                return ResourceManager.GetString("NameBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string PhoneBlock {
            get {
                return ResourceManager.GetString("PhoneBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string PriceBlock {
            get {
                return ResourceManager.GetString("PriceBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price of tasks.
        /// </summary>
        public static string PriceTaskBlock {
            get {
                return ResourceManager.GetString("PriceTaskBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this task?.
        /// </summary>
        public static string QuestionTask {
            get {
                return ResourceManager.GetString("QuestionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to complete this task?.
        /// </summary>
        public static string QuestionTaskComp {
            get {
                return ResourceManager.GetString("QuestionTaskComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove these tasks?.
        /// </summary>
        public static string QuestionTasks {
            get {
                return ResourceManager.GetString("QuestionTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplication version: 1.1.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice shared.
        /// </summary>
        public static string ShareInvoiceDesc {
            get {
                return ResourceManager.GetString("ShareInvoiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice shared!.
        /// </summary>
        public static string ShareInvoiceTitle {
            get {
                return ResourceManager.GetString("ShareInvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swift/bic.
        /// </summary>
        public static string SwifBlock {
            get {
                return ResourceManager.GetString("SwifBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string TaskHeader {
            get {
                return ResourceManager.GetString("TaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string TasksHeader {
            get {
                return ResourceManager.GetString("TasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string TitleBlock {
            get {
                return ResourceManager.GetString("TitleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value per hour.
        /// </summary>
        public static string ValueBlock {
            get {
                return ResourceManager.GetString("ValueBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem installing Voice Commands. The details are provided below. HResult:
        /// {0:X} : {1}.
        /// </summary>
        public static string VoiceCommandInstallErrorTemplate {
            get {
                return ResourceManager.GetString("VoiceCommandInstallErrorTemplate", resourceCulture);
            }
        }
    }
}
